# Generated by Django 2.0.3 on 2019-05-02 11:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 2, 11, 4, 20, 238893), help_text='发布日期', verbose_name='发布日期'),
        ),
        migrations.AlterField(
            model_name='item',
            name='categorys',
            field=models.ForeignKey(help_text='大类', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='article.Category'),
        ),
    ]
