# Generated by Django 2.0.3 on 2019-05-02 11:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20190502_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 2, 11, 35, 40, 420995), help_text='发布日期', verbose_name='发布日期'),
        ),
    ]
