# Generated by Django 2.0.3 on 2019-05-02 11:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20190502_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 2, 11, 44, 57, 860650), help_text='发布日期', verbose_name='发布日期'),
        ),
    ]
